### ISSUE TITLE
Build issues with --target=powerpc64le-unknown-linux-gnu

### ISSUE THREAD

**Issue by runlevel5** [XuShaohua/nc#32]
Version: 0.8.20

Steps to reproduce:

```
$ uname -ar
Linux shrimp-paste 6.8.9-300.fc40.ppc64le #1 SMP Thu May  2 18:35:21 UTC 2024 ppc64le GNU/Linux (Fedora 40)

$ rustc --version
rustc 1.77.0 (aedd173a2 2024-03-17)

$ cargo build --release
    Updating crates.io index
  Downloaded cc v1.0.98
  Downloaded 1 crate (76.8 KB) in 0.15s
   Compiling cc v1.0.98
   Compiling nc v0.8.20 (/home/tle/Work/nc)
error[E0412]: cannot find type `ucontext_t` in this scope
    --> src/platform/linux-ppc64/call.rs:7103:41
     |
7103 | pub unsafe fn swapcontext(old_ctx: &mut ucontext_t, ctx: &ucontext_t) -> Result<(), Errno> {
     |                                         ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ucontext_t` in this scope
    --> src/platform/linux-ppc64/call.rs:7103:59
     |
7103 | pub unsafe fn swapcontext(old_ctx: &mut ucontext_t, ctx: &ucontext_t) -> Result<(), Errno> {
     |                                                           ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ucontext_t` in this scope
    --> src/platform/linux-ppc64/call.rs:7104:39
     |
7104 |     let old_ctx_ptr = old_ctx as *mut ucontext_t as usize;
     |                                       ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ucontext_t` in this scope
    --> src/platform/linux-ppc64/call.rs:7105:33
     |
7105 |     let ctx_ptr = ctx as *const ucontext_t as usize;
     |                                 ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `nc` (lib) due to 4 previous errors
```

**Comment by runlevel5** [comment]
I could successfully compile with v0.8.21
